### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by hihiee** [phillip0726/NaverBlog-Twitter-Youtube-crawling#1]
우선 귀중한 자료를 공유해주셔서 정말 감사합니다.
안녕하세요. 저는 크롤링을 공부하고자 하는 학생입니다. 부끄럽지만 크롤러의 사용법에 대해 여쭈어보고자 글을 남기게 되었습니다. 메일로 연락드릴 방법이 없을까 찾아보았는데 발견하지 못하여 부득이하게 이슈 란에 글을 남깁니다. 죄송합니다.

다름이 아니라 깃헙에 작성해주신 네이버 블로그 크롤러를 사용하고 싶은데, 그 방법을 여쭤봐도 될까요?
Read.me 에 적어두신 것처럼 git clone ~ pip install 까지의 3줄을 터미널에 복사하여 설치하였고, (이렇게 하는 게 맞는지 확신이 들지 않지만) 네이버 크롤러.py 의 코드를 쥬피터 노트에 복사하여 실행시킨 뒤, 그 밑의 셀에 crawling() 를 적고 실행한 후, 차례로 나오는 'Keyword' 와 'Page Num'에 각각 검색어와 크롤링 하고자 하는 페이지 수를 적어 넣었는데, [WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH] 이라는 에러가 발생하여 문의 드립니다.

제가 쓰는 os 환경이 맥 os 여서 해당 문제가 발생하는 것 같아 다시금 윈도우 os 로 돌려보려고 하는데, 혹시 os 문제 말고 제가 크롤러를 사용하는 데 있어 잘못된 점이 있지는 않았을지 여쭈어보고 싶어 글 남깁니다. 

바보 같고 사소한 질문 정말 죄송합니다. 답변 해주신다면 앞으로의 공부에 큰 도움이 될 것 같습니다.
답변 부탁드리겠습니다. 마지막으로 다시 한 번 귀중한 자료를 공유해주셔서 감사드립니다.

**Comment by nut11** [comment]
진짜 바보 같은 질문이었네요... 해결하였습니다. ㅜㅜ 죄송합니다.

**Comment by hihiee** [comment]
진짜 바보 같은 질문이었네요... 해결하였습니다. ㅜㅜ 죄송합니다.
다음 스텝으로 해당 코드 참고해서 포스트 내용도 가져올 수 있을지 코드를 짜봐야겠네요. 정말 감사합니다.
